const ExchangeActions = {
	EXCHANGE_CURRENCY: 'EXCHANGE_CURRENCY',
	GET_CURRENCY: 'GET_CURRENCY',
	GET_CURRENCY_SUCCESS: 'GET_CURRENCY_SUCCESS',
	GET_CURRENCY_FAIL: 'GET_CURRENCY_FAIL',
	UPDATE_FROM_CURRENT_WALLET: 'UPDATE_FROM_CURRENT_WALLET',
	UPDATE_TO_CURRENT_WALLET: 'UPDATE_TO_CURRENT_WALLET',
};

export default ExchangeActions;
